apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-us
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.30.3
    chart: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-us
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.30.3
    chart: istiod
    helm:
      values: |
        global:
          meshID: mpes-mesh
          multiCluster:
            clusterName: cluster-a
          network: network-a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-eu
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.30.3
    chart: base
  destination:
    name: cluster-b
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-eu
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.30.3
    chart: istiod
    helm:
      values: |
        global:
          meshID: mpes-mesh
          multiCluster:
            clusterName: cluster-b
          network: network-b
  destination:
    name: cluster-b
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
