apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-expose-us
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmaous/mpes.git'
    targetRevision: main
    path: kubernetes/platform/istio/expose-services
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-expose-eu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmaous/mpes.git'
    targetRevision: main
    path: kubernetes/platform/istio/expose-services
  destination:
    name: cluster-b
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
