apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubecounter-fleet
  namespace: argocd
spec:
  generators:
      - list:
          elements:
            - clusterName: gke_mmdevops_us-central1_mpes-dev-usc1-gke-primary
              folderName: cluster-a-usc1
            - clusterName: gke_mmdevops_europe-west1_mpes-dev-euw1-gke-secondary
              folderName: cluster-b-euw1
  template:
    metadata:
      name: 'kubecounter-{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/mmaous/kubecounter.git'
        targetRevision: dev # TODO: make it dynamic
        # Dynamically point to overlays based on cluster
        path: 'kube/overlays/{{folderName}}'
      destination:
        server: '{{server}}'
        namespace: kubecounter
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
