apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: mmdevops

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: istio-cacerts
  namespace: istio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: cacerts
    creationPolicy: Owner
  data:
    - secretKey: ca-cert.pem
      remoteRef:
        key: istio-eu-ca-cert
    - secretKey: ca-key.pem
      remoteRef:
        key: istio-eu-ca-key
    - secretKey: root-cert.pem
      remoteRef:
        key: istio-eu-root-cert
    - secretKey: cert-chain.pem
      remoteRef:
        key: istio-eu-cert-chain

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: istio-remote-secret
  namespace: istio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: istio-remote-secret-cluster-a
    creationPolicy: Owner
    template:
      metadata:
        labels:
          istio/multiCluster: "true"
        annotations:
          networking.istio.io/cluster: cluster-a
  data:
    - secretKey: cluster-a
      remoteRef:
        key: istio-remote-secret-us
